2025-03-10 00:58:28,579 - file_reader - INFO - Reading file: data/sample.csv
2025-03-10 00:58:29,442 - file_reader - ERROR - Error reading CSV file: [PATH_NOT_FOUND] Path does not exist: file:/Users/siddharthamahakur/PycharmProjects/SparkETLMaster/data/sample.csv.
Traceback (most recent call last):
  File "/Users/siddharthamahakur/PycharmProjects/SparkETLMaster/ingestion/file_reader.py", line 13, in read_csv
    df = spark.read.csv(file_path, header=True, inferSchema=True)
  File "/Users/siddharthamahakur/PycharmProjects/SparkETLMaster/.venv/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 740, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
  File "/Users/siddharthamahakur/PycharmProjects/SparkETLMaster/.venv/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/Users/siddharthamahakur/PycharmProjects/SparkETLMaster/.venv/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/Users/siddharthamahakur/PycharmProjects/SparkETLMaster/data/sample.csv.
2025-03-10 01:00:09,899 - file_reader - INFO - Reading file: data/sample.csv
2025-03-10 01:00:13,149 - file_reader - INFO - Successfully loaded data!
2025-03-10 01:18:14,514 - file_reader - INFO - Reading file: data/sample.csv
2025-03-10 01:18:17,914 - file_reader - INFO - Successfully loaded data!
2025-03-10 01:21:05,032 - file_reader - INFO - Reading file: data/sample.csv
2025-03-10 01:21:08,485 - file_reader - INFO - Successfully loaded data!
